version: 0.2

phases:
  pre_build:
    commands:
      aws --version
      mvn --version
      java --version

  build:
    commands:
      - echo Building Spring Boot JAR
      - mvn clean package

artifacts:
  files:
    - target/*.jar
