version: 0.2

phases:
  pre_build:
    commands:
      - aws codeartifact login --tool maven --domain mave-repo --domain-owner 117327731569 --repository maven-code-build-repo --region us-east-1
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 117327731569.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Spring Boot JAR
      - mvn clean package
      - docker build -t java-springboot-app .
      - docker tag java-springboot-app:latest 117327731569.dkr.ecr.us-east-1.amazonaws.com/springboot-erc:latest

  post_build:
    commands:
      - docker push 117327731569.dkr.ecr.us-east-1.amazonaws.com/springboot-erc:latest

artifacts:
  files:
    - target/*.jar
